version: '3.0'
services:
  php:
    image: php:7.4-fpm
    volumes:
      - './public:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './public:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
